### ISSUE TITLE
Send confirmation email on register.

### ISSUE THREAD

**Issue by akashsara** [svce-interrupt/Interrupt18-Website#10]
Basic stuff - 
Dear <participant name>
thank you for registering blah blah blah 

If needed we can add a little flair. We can say "Fun Fact: X people from your college have registered so far". If X = 1, say that they're the first etc.

**Comment by akashsara** [comment]
Change email contents to:

Hello <Name>!
Thanks for registering for Interrupt 2018! We're glad to have you. You can use your phone number (<Phone Number>) to login along with the password you chose. If you have any issues, feel free to contact us.

Just to confirm, these are the events that you registered for:

<List of Events>

Regards,
The Interrupt 2018 Organizing Team

**Comment by SHRIRAM0509** [comment]
Are the events finalised? The schema should be changed as well.

**Comment by akashsara** [comment]
Events are all finalized.

**Comment by SHRIRAM0509** [comment]
This one's over
