### ISSUE TITLE
No HTTPS support

### ISSUE THREAD

**Issue by Tchinmai7** [svce-interrupt/Interrupt18-Website#24]
There's no HTTPS support, on a page that collects user data. Use LetsEncrypt to get free SSL certs.

**Comment by ArjArav98** [comment]
Alright cool, I'm on it.

**Comment by akashsara** [comment]
Done.

**Comment by Tchinmai7** [comment]
It's not defaulting to HTTPS. Redirect all port 80 connections to 443 by default.
